/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : GQL.g
 *     -                            On : 2011-09-15 18:54:32
 *     -                for the parser : GQLParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser 
GQLParser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pGQLParser, which is returned from a call to GQLParserNew().
 *
 * The methods in pGQLParser are  as follows:
 *
 *  - 
 void
      pGQLParser->statement(pGQLParser)
 *  - 
 void
      pGQLParser->select_statement(pGQLParser)
 *  - 
 void
      pGQLParser->table_name(pGQLParser)
 *  - 
 void
      pGQLParser->where_section(pGQLParser)
 *  - 
 void
      pGQLParser->condition_list(pGQLParser)
 *  - 
 void
      pGQLParser->condition(pGQLParser)
 *  - 
 void
      pGQLParser->condition_operator(pGQLParser)
 *  - 
 void
      pGQLParser->sort_section(pGQLParser)
 *  - 
 void
      pGQLParser->sort_specification_list(pGQLParser)
 *  - 
 void
      pGQLParser->sort_specification(pGQLParser)
 *  - 
 void
      pGQLParser->ordering_specification(pGQLParser)
 *  - 
 void
      pGQLParser->property(pGQLParser)
 *  - 
 void
      pGQLParser->value(pGQLParser)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_GQLParser_H
#define _GQLParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

    #include <cybergarage/sql/SQLParser.h>


#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct GQLParser_Ctx_struct GQLParser, * pGQLParser;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
GQLParser

 */
struct GQLParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;

     void
     (*statement)	(struct GQLParser_Ctx_struct * ctx, uSQL::SQLParser *sqlParser);

     void
     (*select_statement)	(struct GQLParser_Ctx_struct * ctx);

     void
     (*table_name)	(struct GQLParser_Ctx_struct * ctx);

     void
     (*where_section)	(struct GQLParser_Ctx_struct * ctx);

     void
     (*condition_list)	(struct GQLParser_Ctx_struct * ctx);

     void
     (*condition)	(struct GQLParser_Ctx_struct * ctx);

     void
     (*condition_operator)	(struct GQLParser_Ctx_struct * ctx);

     void
     (*sort_section)	(struct GQLParser_Ctx_struct * ctx);

     void
     (*sort_specification_list)	(struct GQLParser_Ctx_struct * ctx);

     void
     (*sort_specification)	(struct GQLParser_Ctx_struct * ctx);

     void
     (*ordering_specification)	(struct GQLParser_Ctx_struct * ctx);

     void
     (*property)	(struct GQLParser_Ctx_struct * ctx);

     void
     (*value)	(struct GQLParser_Ctx_struct * ctx);
    // Delegated rules

    const char * (*getGrammarFileName)();
    void            (*reset)  (struct GQLParser_Ctx_struct * ctx);
    void	    (*free)   (struct GQLParser_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pGQLParser GQLParserNew         (
pANTLR3_COMMON_TOKEN_STREAM
 instream);
ANTLR3_API pGQLParser GQLParserNewSSD      (
pANTLR3_COMMON_TOKEN_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
parser
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define A      4
#define ANCESTOR      5
#define AND      6
#define ASC      7
#define ASTERISK      8
#define B      9
#define BY      10
#define C      11
#define COMMENT      12
#define D      13
#define DESC      14
#define E      15
#define EQ      16
#define F      17
#define FROM      18
#define G      19
#define GE      20
#define GT      21
#define H      22
#define I      23
#define ID      24
#define IN      25
#define IS      26
#define J      27
#define K      28
#define L      29
#define LE      30
#define LIMIT      31
#define M      32
#define N      33
#define NOTEQ      34
#define O      35
#define OFFSET      36
#define OP_LT      37
#define ORDER      38
#define P      39
#define Q      40
#define R      41
#define S      42
#define SELECT      43
#define T      44
#define U      45
#define V      46
#define W      47
#define WHERE      48
#define X      49
#define Y      50
#define Z      51
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for GQLParser
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
