/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : GQL.g
 *     -                            On : 2011-12-02 15:20:26
 *     -                for the parser : GQLParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "GQLParser.h"
/* ----------------------------------------- */

/******************************************************************
*
* uSQL for C++
*
* GQL.g
*
* Copyright (C) Satoshi Konno 2011
*
* This is licensed under BSD-style license, see file COPYING.
*
******************************************************************/




/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pGQLParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pGQLParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pGQLParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pGQLParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   GQLParserTokenNames[54+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "A",
        (pANTLR3_UINT8) "ANCESTOR",
        (pANTLR3_UINT8) "AND",
        (pANTLR3_UINT8) "ASC",
        (pANTLR3_UINT8) "ASTERISK",
        (pANTLR3_UINT8) "B",
        (pANTLR3_UINT8) "BY",
        (pANTLR3_UINT8) "C",
        (pANTLR3_UINT8) "COMMA",
        (pANTLR3_UINT8) "COMMENT",
        (pANTLR3_UINT8) "D",
        (pANTLR3_UINT8) "DESC",
        (pANTLR3_UINT8) "DIGIT",
        (pANTLR3_UINT8) "E",
        (pANTLR3_UINT8) "EQ",
        (pANTLR3_UINT8) "EscapeSequence",
        (pANTLR3_UINT8) "F",
        (pANTLR3_UINT8) "FROM",
        (pANTLR3_UINT8) "G",
        (pANTLR3_UINT8) "GE",
        (pANTLR3_UINT8) "GT",
        (pANTLR3_UINT8) "H",
        (pANTLR3_UINT8) "I",
        (pANTLR3_UINT8) "ID",
        (pANTLR3_UINT8) "IN",
        (pANTLR3_UINT8) "IS",
        (pANTLR3_UINT8) "J",
        (pANTLR3_UINT8) "K",
        (pANTLR3_UINT8) "L",
        (pANTLR3_UINT8) "LE",
        (pANTLR3_UINT8) "LIMIT",
        (pANTLR3_UINT8) "M",
        (pANTLR3_UINT8) "N",
        (pANTLR3_UINT8) "NOTEQ",
        (pANTLR3_UINT8) "NUMBER",
        (pANTLR3_UINT8) "O",
        (pANTLR3_UINT8) "OFFSET",
        (pANTLR3_UINT8) "OP_LT",
        (pANTLR3_UINT8) "ORDER",
        (pANTLR3_UINT8) "P",
        (pANTLR3_UINT8) "Q",
        (pANTLR3_UINT8) "R",
        (pANTLR3_UINT8) "S",
        (pANTLR3_UINT8) "SELECT",
        (pANTLR3_UINT8) "STRING",
        (pANTLR3_UINT8) "T",
        (pANTLR3_UINT8) "U",
        (pANTLR3_UINT8) "V",
        (pANTLR3_UINT8) "W",
        (pANTLR3_UINT8) "WHERE",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "X",
        (pANTLR3_UINT8) "Y",
        (pANTLR3_UINT8) "Z"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 void
	statement    (pGQLParser ctx, uSQL::SQLParser *sqlParser);
static 
 void
	select_statement    (pGQLParser ctx, uSQL::SQLStatement *sqlStmt);
static 
 void
	table_name    (pGQLParser ctx, uSQL::SQLFrom *sqlFrom);
static 
 uSQL::SQLFrom *
	table_list    (pGQLParser ctx);
static 
 uSQL::SQLWhere *
	where_section    (pGQLParser ctx);
static 
 void
	condition_list    (pGQLParser ctx, uSQL::SQLWhere *sqlWhere);
static 
 void
	condition    (pGQLParser ctx, uSQL::SQLWhere *sqlWhere);
static 
 uSQL::SQLExpression *
	expression_atom    (pGQLParser ctx);
static 
 uSQL::SQLOperator *
	condition_operator    (pGQLParser ctx);
static 
 uSQL::SQLOrderBy *
	sort_section    (pGQLParser ctx);
static 
 void
	sort_specification_list    (pGQLParser ctx, uSQL::SQLOrderBy *sqlOrders);
static 
 void
	sort_specification    (pGQLParser ctx, uSQL::SQLOrderBy *sqlOrders);
static 
 GQLParser_ordering_specification_return
	ordering_specification    (pGQLParser ctx);
static 
 uSQL::SQLLimit *
	limit_section    (pGQLParser ctx);
static 
 void
	limit_offset    (pGQLParser ctx, uSQL::SQLLimit *sqlLimit);
static 
 uSQL::SQLOffset *
	offset_section    (pGQLParser ctx);
static 
 GQLParser_property_return
	property    (pGQLParser ctx);
static 
 GQLParser_value_return
	value    (pGQLParser ctx);
static void	GQLParserFree(pGQLParser ctx);
static void     GQLParserReset (pGQLParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "GQL.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new GQLParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pGQLParser
GQLParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return GQLParserNewSSD(instream, NULL);
}

/** \brief Create a new GQLParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pGQLParser
GQLParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pGQLParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pGQLParser) ANTLR3_CALLOC(1, sizeof(GQLParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in GQLParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our GQLParser interface
     */
    ctx->statement	= statement;
    ctx->select_statement	= select_statement;
    ctx->table_name	= table_name;
    ctx->table_list	= table_list;
    ctx->where_section	= where_section;
    ctx->condition_list	= condition_list;
    ctx->condition	= condition;
    ctx->expression_atom	= expression_atom;
    ctx->condition_operator	= condition_operator;
    ctx->sort_section	= sort_section;
    ctx->sort_specification_list	= sort_specification_list;
    ctx->sort_specification	= sort_specification;
    ctx->ordering_specification	= ordering_specification;
    ctx->limit_section	= limit_section;
    ctx->limit_offset	= limit_offset;
    ctx->offset_section	= offset_section;
    ctx->property	= property;
    ctx->value	= value;
    ctx->free			= GQLParserFree;
    ctx->reset			= GQLParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */

    /* Install the token table
     */
    PSRSTATE->tokenNames   = GQLParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
GQLParserReset (pGQLParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 GQLParserFree(pGQLParser ctx)
 {
    /* Free any scope memory
     */

	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return GQLParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_select_statement_in_statement61  */
static	ANTLR3_BITWORD FOLLOW_select_statement_in_statement61_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_select_statement_in_statement61	= { FOLLOW_select_statement_in_statement61_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SELECT_in_select_statement82  */
static	ANTLR3_BITWORD FOLLOW_SELECT_in_select_statement82_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_SELECT_in_select_statement82	= { FOLLOW_SELECT_in_select_statement82_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASTERISK_in_select_statement84  */
static	ANTLR3_BITWORD FOLLOW_ASTERISK_in_select_statement84_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000200000) };
static  ANTLR3_BITSET_LIST FOLLOW_ASTERISK_in_select_statement84	= { FOLLOW_ASTERISK_in_select_statement84_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FROM_in_select_statement86  */
static	ANTLR3_BITWORD FOLLOW_FROM_in_select_statement86_bits[]	= { ANTLR3_UINT64_LIT(0x0000000008000000) };
static  ANTLR3_BITSET_LIST FOLLOW_FROM_in_select_statement86	= { FOLLOW_FROM_in_select_statement86_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_table_list_in_select_statement90  */
static	ANTLR3_BITWORD FOLLOW_table_list_in_select_statement90_bits[]	= { ANTLR3_UINT64_LIT(0x0020050400000002) };
static  ANTLR3_BITSET_LIST FOLLOW_table_list_in_select_statement90	= { FOLLOW_table_list_in_select_statement90_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_where_section_in_select_statement95  */
static	ANTLR3_BITWORD FOLLOW_where_section_in_select_statement95_bits[]	= { ANTLR3_UINT64_LIT(0x0000050400000002) };
static  ANTLR3_BITSET_LIST FOLLOW_where_section_in_select_statement95	= { FOLLOW_where_section_in_select_statement95_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sort_section_in_select_statement102  */
static	ANTLR3_BITWORD FOLLOW_sort_section_in_select_statement102_bits[]	= { ANTLR3_UINT64_LIT(0x0000010400000002) };
static  ANTLR3_BITSET_LIST FOLLOW_sort_section_in_select_statement102	= { FOLLOW_sort_section_in_select_statement102_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_limit_section_in_select_statement109  */
static	ANTLR3_BITWORD FOLLOW_limit_section_in_select_statement109_bits[]	= { ANTLR3_UINT64_LIT(0x0000010000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_limit_section_in_select_statement109	= { FOLLOW_limit_section_in_select_statement109_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_offset_section_in_select_statement116  */
static	ANTLR3_BITWORD FOLLOW_offset_section_in_select_statement116_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_offset_section_in_select_statement116	= { FOLLOW_offset_section_in_select_statement116_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_table_name135  */
static	ANTLR3_BITWORD FOLLOW_ID_in_table_name135_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_table_name135	= { FOLLOW_ID_in_table_name135_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_table_name_in_table_list159  */
static	ANTLR3_BITWORD FOLLOW_table_name_in_table_list159_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001002) };
static  ANTLR3_BITSET_LIST FOLLOW_table_name_in_table_list159	= { FOLLOW_table_name_in_table_list159_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_COMMA_in_table_list164  */
static	ANTLR3_BITWORD FOLLOW_COMMA_in_table_list164_bits[]	= { ANTLR3_UINT64_LIT(0x0000000008000000) };
static  ANTLR3_BITSET_LIST FOLLOW_COMMA_in_table_list164	= { FOLLOW_COMMA_in_table_list164_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_table_name_in_table_list166  */
static	ANTLR3_BITWORD FOLLOW_table_name_in_table_list166_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001002) };
static  ANTLR3_BITSET_LIST FOLLOW_table_name_in_table_list166	= { FOLLOW_table_name_in_table_list166_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WHERE_in_where_section190  */
static	ANTLR3_BITWORD FOLLOW_WHERE_in_where_section190_bits[]	= { ANTLR3_UINT64_LIT(0x0001000008000020) };
static  ANTLR3_BITSET_LIST FOLLOW_WHERE_in_where_section190	= { FOLLOW_WHERE_in_where_section190_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_condition_list_in_where_section192  */
static	ANTLR3_BITWORD FOLLOW_condition_list_in_where_section192_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_condition_list_in_where_section192	= { FOLLOW_condition_list_in_where_section192_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_condition_in_condition_list207  */
static	ANTLR3_BITWORD FOLLOW_condition_in_condition_list207_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000042) };
static  ANTLR3_BITSET_LIST FOLLOW_condition_in_condition_list207	= { FOLLOW_condition_in_condition_list207_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_AND_in_condition_list211  */
static	ANTLR3_BITWORD FOLLOW_AND_in_condition_list211_bits[]	= { ANTLR3_UINT64_LIT(0x0001000008000020) };
static  ANTLR3_BITSET_LIST FOLLOW_AND_in_condition_list211	= { FOLLOW_AND_in_condition_list211_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_condition_in_condition_list213  */
static	ANTLR3_BITWORD FOLLOW_condition_in_condition_list213_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000042) };
static  ANTLR3_BITSET_LIST FOLLOW_condition_in_condition_list213	= { FOLLOW_condition_in_condition_list213_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expression_atom_in_condition231  */
static	ANTLR3_BITWORD FOLLOW_expression_atom_in_condition231_bits[]	= { ANTLR3_UINT64_LIT(0x0000022201840000) };
static  ANTLR3_BITSET_LIST FOLLOW_expression_atom_in_condition231	= { FOLLOW_expression_atom_in_condition231_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_condition_operator_in_condition235  */
static	ANTLR3_BITWORD FOLLOW_condition_operator_in_condition235_bits[]	= { ANTLR3_UINT64_LIT(0x0001000008000000) };
static  ANTLR3_BITSET_LIST FOLLOW_condition_operator_in_condition235	= { FOLLOW_condition_operator_in_condition235_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expression_atom_in_condition239  */
static	ANTLR3_BITWORD FOLLOW_expression_atom_in_condition239_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_expression_atom_in_condition239	= { FOLLOW_expression_atom_in_condition239_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_property_in_condition246  */
static	ANTLR3_BITWORD FOLLOW_property_in_condition246_bits[]	= { ANTLR3_UINT64_LIT(0x0000000010000000) };
static  ANTLR3_BITSET_LIST FOLLOW_property_in_condition246	= { FOLLOW_property_in_condition246_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IN_in_condition248  */
static	ANTLR3_BITWORD FOLLOW_IN_in_condition248_bits[]	= { ANTLR3_UINT64_LIT(0x0001000000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_IN_in_condition248	= { FOLLOW_IN_in_condition248_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_value_in_condition250  */
static	ANTLR3_BITWORD FOLLOW_value_in_condition250_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_value_in_condition250	= { FOLLOW_value_in_condition250_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ANCESTOR_in_condition255  */
static	ANTLR3_BITWORD FOLLOW_ANCESTOR_in_condition255_bits[]	= { ANTLR3_UINT64_LIT(0x0000000020000000) };
static  ANTLR3_BITSET_LIST FOLLOW_ANCESTOR_in_condition255	= { FOLLOW_ANCESTOR_in_condition255_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IS_in_condition258  */
static	ANTLR3_BITWORD FOLLOW_IS_in_condition258_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_IS_in_condition258	= { FOLLOW_IS_in_condition258_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_property_in_expression_atom280  */
static	ANTLR3_BITWORD FOLLOW_property_in_expression_atom280_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_property_in_expression_atom280	= { FOLLOW_property_in_expression_atom280_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_value_in_expression_atom287  */
static	ANTLR3_BITWORD FOLLOW_value_in_expression_atom287_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_value_in_expression_atom287	= { FOLLOW_value_in_expression_atom287_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EQ_in_condition_operator310  */
static	ANTLR3_BITWORD FOLLOW_EQ_in_condition_operator310_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EQ_in_condition_operator310	= { FOLLOW_EQ_in_condition_operator310_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_OP_LT_in_condition_operator317  */
static	ANTLR3_BITWORD FOLLOW_OP_LT_in_condition_operator317_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_OP_LT_in_condition_operator317	= { FOLLOW_OP_LT_in_condition_operator317_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LE_in_condition_operator324  */
static	ANTLR3_BITWORD FOLLOW_LE_in_condition_operator324_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_LE_in_condition_operator324	= { FOLLOW_LE_in_condition_operator324_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_GT_in_condition_operator331  */
static	ANTLR3_BITWORD FOLLOW_GT_in_condition_operator331_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_GT_in_condition_operator331	= { FOLLOW_GT_in_condition_operator331_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_GE_in_condition_operator338  */
static	ANTLR3_BITWORD FOLLOW_GE_in_condition_operator338_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_GE_in_condition_operator338	= { FOLLOW_GE_in_condition_operator338_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NOTEQ_in_condition_operator345  */
static	ANTLR3_BITWORD FOLLOW_NOTEQ_in_condition_operator345_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NOTEQ_in_condition_operator345	= { FOLLOW_NOTEQ_in_condition_operator345_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ORDER_in_sort_section368  */
static	ANTLR3_BITWORD FOLLOW_ORDER_in_sort_section368_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_ORDER_in_sort_section368	= { FOLLOW_ORDER_in_sort_section368_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_BY_in_sort_section370  */
static	ANTLR3_BITWORD FOLLOW_BY_in_sort_section370_bits[]	= { ANTLR3_UINT64_LIT(0x0000000008000000) };
static  ANTLR3_BITSET_LIST FOLLOW_BY_in_sort_section370	= { FOLLOW_BY_in_sort_section370_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sort_specification_list_in_sort_section372  */
static	ANTLR3_BITWORD FOLLOW_sort_specification_list_in_sort_section372_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_sort_specification_list_in_sort_section372	= { FOLLOW_sort_specification_list_in_sort_section372_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sort_specification_in_sort_specification_list387  */
static	ANTLR3_BITWORD FOLLOW_sort_specification_in_sort_specification_list387_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000042) };
static  ANTLR3_BITSET_LIST FOLLOW_sort_specification_in_sort_specification_list387	= { FOLLOW_sort_specification_in_sort_specification_list387_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_AND_in_sort_specification_list391  */
static	ANTLR3_BITWORD FOLLOW_AND_in_sort_specification_list391_bits[]	= { ANTLR3_UINT64_LIT(0x0000000008000000) };
static  ANTLR3_BITSET_LIST FOLLOW_AND_in_sort_specification_list391	= { FOLLOW_AND_in_sort_specification_list391_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sort_specification_in_sort_specification_list393  */
static	ANTLR3_BITWORD FOLLOW_sort_specification_in_sort_specification_list393_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000042) };
static  ANTLR3_BITSET_LIST FOLLOW_sort_specification_in_sort_specification_list393	= { FOLLOW_sort_specification_in_sort_specification_list393_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_property_in_sort_specification410  */
static	ANTLR3_BITWORD FOLLOW_property_in_sort_specification410_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008082) };
static  ANTLR3_BITSET_LIST FOLLOW_property_in_sort_specification410	= { FOLLOW_property_in_sort_specification410_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ordering_specification_in_sort_specification413  */
static	ANTLR3_BITWORD FOLLOW_ordering_specification_in_sort_specification413_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ordering_specification_in_sort_specification413	= { FOLLOW_ordering_specification_in_sort_specification413_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LIMIT_in_limit_section454  */
static	ANTLR3_BITWORD FOLLOW_LIMIT_in_limit_section454_bits[]	= { ANTLR3_UINT64_LIT(0x0000004000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_LIMIT_in_limit_section454	= { FOLLOW_LIMIT_in_limit_section454_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_limit_offset_in_limit_section457  */
static	ANTLR3_BITWORD FOLLOW_limit_offset_in_limit_section457_bits[]	= { ANTLR3_UINT64_LIT(0x0000004000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_limit_offset_in_limit_section457	= { FOLLOW_limit_offset_in_limit_section457_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NUMBER_in_limit_section462  */
static	ANTLR3_BITWORD FOLLOW_NUMBER_in_limit_section462_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NUMBER_in_limit_section462	= { FOLLOW_NUMBER_in_limit_section462_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NUMBER_in_limit_offset477  */
static	ANTLR3_BITWORD FOLLOW_NUMBER_in_limit_offset477_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_NUMBER_in_limit_offset477	= { FOLLOW_NUMBER_in_limit_offset477_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_COMMA_in_limit_offset479  */
static	ANTLR3_BITWORD FOLLOW_COMMA_in_limit_offset479_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_COMMA_in_limit_offset479	= { FOLLOW_COMMA_in_limit_offset479_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_OFFSET_in_offset_section502  */
static	ANTLR3_BITWORD FOLLOW_OFFSET_in_offset_section502_bits[]	= { ANTLR3_UINT64_LIT(0x0000004000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_OFFSET_in_offset_section502	= { FOLLOW_OFFSET_in_offset_section502_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NUMBER_in_offset_section504  */
static	ANTLR3_BITWORD FOLLOW_NUMBER_in_offset_section504_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NUMBER_in_offset_section504	= { FOLLOW_NUMBER_in_offset_section504_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_property521  */
static	ANTLR3_BITWORD FOLLOW_ID_in_property521_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_property521	= { FOLLOW_ID_in_property521_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_value533  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_value533_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_value533	= { FOLLOW_STRING_in_value533_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start statement
 * GQL.g:38:1: statement[uSQL::SQLParser *sqlParser] : select_statement[stmt] ;
 */
static void
statement(pGQLParser ctx, uSQL::SQLParser *sqlParser)
{
    /* Initialize rule variables
     */


    		uSQL::SQLStatement *stmt = new uSQL::SQLStatement();
    		sqlParser->addStatement(stmt);
    	
    {
        // GQL.g:43:2: ( select_statement[stmt] )
        // GQL.g:43:4: select_statement[stmt]
        {
            FOLLOWPUSH(FOLLOW_select_statement_in_statement61);
            select_statement(ctx, stmt);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulestatementEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulestatementEx; /* Prevent compiler warnings */
    rulestatementEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end statement */

/**
 * $ANTLR start select_statement
 * GQL.g:46:1: select_statement[uSQL::SQLStatement *sqlStmt] : SELECT ASTERISK FROM tl= table_list (ws= where_section )? (ss= sort_section )? (ls= limit_section )? (os= offset_section )? ;
 */
static void
select_statement(pGQLParser ctx, uSQL::SQLStatement *sqlStmt)
{
    uSQL::SQLFrom * tl;
    #undef	RETURN_TYPE_tl
    #define	RETURN_TYPE_tl uSQL::SQLFrom *

    uSQL::SQLWhere * ws;
    #undef	RETURN_TYPE_ws
    #define	RETURN_TYPE_ws uSQL::SQLWhere *

    uSQL::SQLOrderBy * ss;
    #undef	RETURN_TYPE_ss
    #define	RETURN_TYPE_ss uSQL::SQLOrderBy *

    uSQL::SQLLimit * ls;
    #undef	RETURN_TYPE_ls
    #define	RETURN_TYPE_ls uSQL::SQLLimit *

    uSQL::SQLOffset * os;
    #undef	RETURN_TYPE_os
    #define	RETURN_TYPE_os uSQL::SQLOffset *

    /* Initialize rule variables
     */


    		tl = NULL;
    		ws = NULL;
    		ss = NULL;
    		ls = NULL;
    		os = NULL;
    	
    {
        // GQL.g:54:2: ( SELECT ASTERISK FROM tl= table_list (ws= where_section )? (ss= sort_section )? (ls= limit_section )? (os= offset_section )? )
        // GQL.g:54:4: SELECT ASTERISK FROM tl= table_list (ws= where_section )? (ss= sort_section )? (ls= limit_section )? (os= offset_section )?
        {
             MATCHT(SELECT, &FOLLOW_SELECT_in_select_statement82);
            if  (HASEXCEPTION())
            {
                goto ruleselect_statementEx;
            }


             MATCHT(ASTERISK, &FOLLOW_ASTERISK_in_select_statement84);
            if  (HASEXCEPTION())
            {
                goto ruleselect_statementEx;
            }


             MATCHT(FROM, &FOLLOW_FROM_in_select_statement86);
            if  (HASEXCEPTION())
            {
                goto ruleselect_statementEx;
            }


            FOLLOWPUSH(FOLLOW_table_list_in_select_statement90);
            tl=table_list(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleselect_statementEx;
            }


            // GQL.g:54:39: (ws= where_section )?
            {
                int alt1=2;
                switch ( LA(1) )
                {
                    case WHERE:
                    	{
                    		alt1=1;
                    	}
                        break;
                }

                switch (alt1)
                {
            	case 1:
            	    // GQL.g:54:40: ws= where_section
            	    {
            	        FOLLOWPUSH(FOLLOW_where_section_in_select_statement95);
            	        ws=where_section(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleselect_statementEx;
            	        }


            	    }
            	    break;

                }
            }

            // GQL.g:54:59: (ss= sort_section )?
            {
                int alt2=2;
                switch ( LA(1) )
                {
                    case ORDER:
                    	{
                    		alt2=1;
                    	}
                        break;
                }

                switch (alt2)
                {
            	case 1:
            	    // GQL.g:54:60: ss= sort_section
            	    {
            	        FOLLOWPUSH(FOLLOW_sort_section_in_select_statement102);
            	        ss=sort_section(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleselect_statementEx;
            	        }


            	    }
            	    break;

                }
            }

            // GQL.g:54:78: (ls= limit_section )?
            {
                int alt3=2;
                switch ( LA(1) )
                {
                    case LIMIT:
                    	{
                    		alt3=1;
                    	}
                        break;
                }

                switch (alt3)
                {
            	case 1:
            	    // GQL.g:54:79: ls= limit_section
            	    {
            	        FOLLOWPUSH(FOLLOW_limit_section_in_select_statement109);
            	        ls=limit_section(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleselect_statementEx;
            	        }


            	    }
            	    break;

                }
            }

            // GQL.g:54:98: (os= offset_section )?
            {
                int alt4=2;
                switch ( LA(1) )
                {
                    case OFFSET:
                    	{
                    		alt4=1;
                    	}
                        break;
                }

                switch (alt4)
                {
            	case 1:
            	    // GQL.g:54:99: os= offset_section
            	    {
            	        FOLLOWPUSH(FOLLOW_offset_section_in_select_statement116);
            	        os=offset_section(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleselect_statementEx;
            	        }


            	    }
            	    break;

                }
            }

            {

                		// SELECT
                		uSQL::SQLSelect *sqlCmd = new uSQL::SQLSelect();
                		sqlStmt->addChildNode(sqlCmd);

                		// ASTERISK
                		/*
                		uSQL::SQLColumns *sqlColumns = new uSQL::SQLColumns();
                		sqlStmt->addChildNode(sqlColumns);
                		uSQL::SQLColumn *sqlColumn = new uSQL::SQLColumn();
                		sqlColumn->setName("*");
                		sqlColumns->addChildNode(sqlColumn);
                		*/
                		
                		// TABLE		
                		sqlStmt->addChildNode(tl);
                		
                		// WHERE		
                		if (ws)
                			sqlStmt->addChildNode(ws);
                			
                		// ORDER BY		
                		if (ss)
                			sqlStmt->addChildNode(ss);
                			
                		// LIMIT		
                		if (ls)
                			sqlStmt->addChildNode(ls);

                		// OFFSET		
                		if (os)
                			sqlStmt->addChildNode(os);

                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleselect_statementEx; /* Prevent compiler warnings */
    ruleselect_statementEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end select_statement */

/**
 * $ANTLR start table_name
 * GQL.g:91:1: table_name[uSQL::SQLFrom *sqlFrom] : ID ;
 */
static void
table_name(pGQLParser ctx, uSQL::SQLFrom *sqlFrom)
{
    pANTLR3_COMMON_TOKEN    ID1;

    /* Initialize rule variables
     */

    ID1       = NULL;

    {
        // GQL.g:92:2: ( ID )
        // GQL.g:92:4: ID
        {
            ID1 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_table_name135);
            if  (HASEXCEPTION())
            {
                goto ruletable_nameEx;
            }


            {

                		uSQL::SQLDataSource *sqlTable = new uSQL::SQLDataSource();
                		sqlTable->setValue(CG_ANTLR3_STRING_2_UTF8((ID1->getText(ID1))));
                		sqlFrom->addChildNode(sqlTable);
                	  
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruletable_nameEx; /* Prevent compiler warnings */
    ruletable_nameEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end table_name */

/**
 * $ANTLR start table_list
 * GQL.g:99:1: table_list returns [uSQL::SQLFrom *sqlFrom] : ( table_name[sqlFrom] ) ( COMMA table_name[sqlFrom] )* ;
 */
static uSQL::SQLFrom *
table_list(pGQLParser ctx)
{
    uSQL::SQLFrom * sqlFrom;


    /* Initialize rule variables
     */


    		sqlFrom = new uSQL::SQLFrom();
    	
    {
        // GQL.g:103:2: ( ( table_name[sqlFrom] ) ( COMMA table_name[sqlFrom] )* )
        // GQL.g:103:4: ( table_name[sqlFrom] ) ( COMMA table_name[sqlFrom] )*
        {
            // GQL.g:103:4: ( table_name[sqlFrom] )
            // GQL.g:103:5: table_name[sqlFrom]
            {
                FOLLOWPUSH(FOLLOW_table_name_in_table_list159);
                table_name(ctx, sqlFrom);

                FOLLOWPOP();
                if  (HASEXCEPTION())
                {
                    goto ruletable_listEx;
                }


            }


            // GQL.g:103:26: ( COMMA table_name[sqlFrom] )*

            for (;;)
            {
                int alt5=2;
                switch ( LA(1) )
                {
                case COMMA:
                	{
                		alt5=1;
                	}
                    break;

                }

                switch (alt5)
                {
            	case 1:
            	    // GQL.g:103:27: COMMA table_name[sqlFrom]
            	    {
            	         MATCHT(COMMA, &FOLLOW_COMMA_in_table_list164);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruletable_listEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_table_name_in_table_list166);
            	        table_name(ctx, sqlFrom);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruletable_listEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop5;	/* break out of the loop */
            	    break;
                }
            }
            loop5: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruletable_listEx; /* Prevent compiler warnings */
    ruletable_listEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return sqlFrom;
}
/* $ANTLR end table_list */

/**
 * $ANTLR start where_section
 * GQL.g:106:1: where_section returns [uSQL::SQLWhere *sqlWhere] : WHERE condition_list[sqlWhere] ;
 */
static uSQL::SQLWhere *
where_section(pGQLParser ctx)
{
    uSQL::SQLWhere * sqlWhere;


    /* Initialize rule variables
     */


    		sqlWhere = new uSQL::SQLWhere();
    	
    {
        // GQL.g:110:2: ( WHERE condition_list[sqlWhere] )
        // GQL.g:110:4: WHERE condition_list[sqlWhere]
        {
             MATCHT(WHERE, &FOLLOW_WHERE_in_where_section190);
            if  (HASEXCEPTION())
            {
                goto rulewhere_sectionEx;
            }


            FOLLOWPUSH(FOLLOW_condition_list_in_where_section192);
            condition_list(ctx, sqlWhere);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulewhere_sectionEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulewhere_sectionEx; /* Prevent compiler warnings */
    rulewhere_sectionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return sqlWhere;
}
/* $ANTLR end where_section */

/**
 * $ANTLR start condition_list
 * GQL.g:113:1: condition_list[uSQL::SQLWhere *sqlWhere] : condition[sqlWhere] ( AND condition[sqlWhere] )* ;
 */
static void
condition_list(pGQLParser ctx, uSQL::SQLWhere *sqlWhere)
{
    /* Initialize rule variables
     */

    {
        // GQL.g:114:2: ( condition[sqlWhere] ( AND condition[sqlWhere] )* )
        // GQL.g:114:4: condition[sqlWhere] ( AND condition[sqlWhere] )*
        {
            FOLLOWPUSH(FOLLOW_condition_in_condition_list207);
            condition(ctx, sqlWhere);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulecondition_listEx;
            }


            // GQL.g:114:24: ( AND condition[sqlWhere] )*

            for (;;)
            {
                int alt6=2;
                switch ( LA(1) )
                {
                case AND:
                	{
                		alt6=1;
                	}
                    break;

                }

                switch (alt6)
                {
            	case 1:
            	    // GQL.g:114:25: AND condition[sqlWhere]
            	    {
            	         MATCHT(AND, &FOLLOW_AND_in_condition_list211);
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulecondition_listEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_condition_in_condition_list213);
            	        condition(ctx, sqlWhere);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulecondition_listEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop6;	/* break out of the loop */
            	    break;
                }
            }
            loop6: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto rulecondition_listEx; /* Prevent compiler warnings */
    rulecondition_listEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end condition_list */

/**
 * $ANTLR start condition
 * GQL.g:117:1: condition[uSQL::SQLWhere *sqlWhere] : (exprLeft= expression_atom binOper= condition_operator exprRight= expression_atom | property IN value | ANCESTOR IS );
 */
static void
condition(pGQLParser ctx, uSQL::SQLWhere *sqlWhere)
{
    uSQL::SQLExpression * exprLeft;
    #undef	RETURN_TYPE_exprLeft
    #define	RETURN_TYPE_exprLeft uSQL::SQLExpression *

    uSQL::SQLOperator * binOper;
    #undef	RETURN_TYPE_binOper
    #define	RETURN_TYPE_binOper uSQL::SQLOperator *

    uSQL::SQLExpression * exprRight;
    #undef	RETURN_TYPE_exprRight
    #define	RETURN_TYPE_exprRight uSQL::SQLExpression *

    /* Initialize rule variables
     */

    {
        {
            //  GQL.g:118:2: (exprLeft= expression_atom binOper= condition_operator exprRight= expression_atom | property IN value | ANCESTOR IS )

            ANTLR3_UINT32 alt7;

            alt7=3;

            switch ( LA(1) )
            {
            case ID:
            	{
            		switch ( LA(2) )
            		{
            		case EQ:
            		case GE:
            		case GT:
            		case LE:
            		case NOTEQ:
            		case OP_LT:
            			{
            				alt7=1;
            			}
            		    break;
            		case IN:
            			{
            				alt7=2;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 7;
            		    EXCEPTION->state        = 1;


            		    goto ruleconditionEx;

            		}

            	}
                break;
            case STRING:
            	{
            		alt7=1;
            	}
                break;
            case ANCESTOR:
            	{
            		alt7=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 7;
                EXCEPTION->state        = 0;


                goto ruleconditionEx;

            }

            switch (alt7)
            {
        	case 1:
        	    // GQL.g:118:4: exprLeft= expression_atom binOper= condition_operator exprRight= expression_atom
        	    {
        	        FOLLOWPUSH(FOLLOW_expression_atom_in_condition231);
        	        exprLeft=expression_atom(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleconditionEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_condition_operator_in_condition235);
        	        binOper=condition_operator(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleconditionEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_expression_atom_in_condition239);
        	        exprRight=expression_atom(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleconditionEx;
        	        }


        	        {

        	            		sqlWhere->addExpression(binOper);
        	            		binOper->addExpression(exprLeft);
        	            		binOper->addExpression(exprRight);
        	            	  
        	        }


        	    }
        	    break;
        	case 2:
        	    // GQL.g:123:4: property IN value
        	    {
        	        FOLLOWPUSH(FOLLOW_property_in_condition246);
        	        property(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleconditionEx;
        	        }


        	         MATCHT(IN, &FOLLOW_IN_in_condition248);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleconditionEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_value_in_condition250);
        	        value(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleconditionEx;
        	        }


        	    }
        	    break;
        	case 3:
        	    // GQL.g:124:4: ANCESTOR IS
        	    {
        	         MATCHT(ANCESTOR, &FOLLOW_ANCESTOR_in_condition255);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleconditionEx;
        	        }


        	         MATCHT(IS, &FOLLOW_IS_in_condition258);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleconditionEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleconditionEx; /* Prevent compiler warnings */
    ruleconditionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end condition */

/**
 * $ANTLR start expression_atom
 * GQL.g:127:1: expression_atom returns [uSQL::SQLExpression *sqlExpr] : ( property | value );
 */
static uSQL::SQLExpression *
expression_atom(pGQLParser ctx)
{
    uSQL::SQLExpression * sqlExpr;


    GQLParser_property_return property2;
    #undef	RETURN_TYPE_property2
    #define	RETURN_TYPE_property2 GQLParser_property_return

    GQLParser_value_return value3;
    #undef	RETURN_TYPE_value3
    #define	RETURN_TYPE_value3 GQLParser_value_return

    /* Initialize rule variables
     */


    		sqlExpr = new uSQL::SQLExpression();
    	
    {
        {
            //  GQL.g:131:3: ( property | value )

            ANTLR3_UINT32 alt8;

            alt8=2;

            switch ( LA(1) )
            {
            case ID:
            	{
            		alt8=1;
            	}
                break;
            case STRING:
            	{
            		alt8=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 8;
                EXCEPTION->state        = 0;


                goto ruleexpression_atomEx;

            }

            switch (alt8)
            {
        	case 1:
        	    // GQL.g:131:5: property
        	    {
        	        FOLLOWPUSH(FOLLOW_property_in_expression_atom280);
        	        property2=property(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexpression_atomEx;
        	        }


        	        {

        	            		sqlExpr->setValue(CG_ANTLR3_STRING_2_UTF8((STRSTREAM->toStringTT(STRSTREAM, property2.start, property2.stop))
        	            ));
        	            	  
        	        }


        	    }
        	    break;
        	case 2:
        	    // GQL.g:134:4: value
        	    {
        	        FOLLOWPUSH(FOLLOW_value_in_expression_atom287);
        	        value3=value(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexpression_atomEx;
        	        }


        	        {

        	            			sqlExpr->setValue(CG_ANTLR3_STRING_2_UTF8((STRSTREAM->toStringTT(STRSTREAM, value3.start, value3.stop))
        	            ));
        	            	  
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleexpression_atomEx; /* Prevent compiler warnings */
    ruleexpression_atomEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return sqlExpr;
}
/* $ANTLR end expression_atom */

/**
 * $ANTLR start condition_operator
 * GQL.g:139:1: condition_operator returns [uSQL::SQLOperator *sqlOper] : ( EQ | OP_LT | LE | GT | GE | NOTEQ );
 */
static uSQL::SQLOperator *
condition_operator(pGQLParser ctx)
{
    uSQL::SQLOperator * sqlOper;


    /* Initialize rule variables
     */


    		sqlOper = new uSQL::SQLOperator();
    	
    {
        {
            //  GQL.g:143:2: ( EQ | OP_LT | LE | GT | GE | NOTEQ )

            ANTLR3_UINT32 alt9;

            alt9=6;

            switch ( LA(1) )
            {
            case EQ:
            	{
            		alt9=1;
            	}
                break;
            case OP_LT:
            	{
            		alt9=2;
            	}
                break;
            case LE:
            	{
            		alt9=3;
            	}
                break;
            case GT:
            	{
            		alt9=4;
            	}
                break;
            case GE:
            	{
            		alt9=5;
            	}
                break;
            case NOTEQ:
            	{
            		alt9=6;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 9;
                EXCEPTION->state        = 0;


                goto rulecondition_operatorEx;

            }

            switch (alt9)
            {
        	case 1:
        	    // GQL.g:143:4: EQ
        	    {
        	         MATCHT(EQ, &FOLLOW_EQ_in_condition_operator310);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecondition_operatorEx;
        	        }


        	        {

        	            		sqlOper->setValue(1/*uSQL::SQLOperator::EQ*/);
        	            	  
        	        }


        	    }
        	    break;
        	case 2:
        	    // GQL.g:146:4: OP_LT
        	    {
        	         MATCHT(OP_LT, &FOLLOW_OP_LT_in_condition_operator317);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecondition_operatorEx;
        	        }


        	        {

        	            		sqlOper->setValue(2/*uSQL::SQLOperator::LT*/);
        	            	  
        	        }


        	    }
        	    break;
        	case 3:
        	    // GQL.g:149:4: LE
        	    {
        	         MATCHT(LE, &FOLLOW_LE_in_condition_operator324);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecondition_operatorEx;
        	        }


        	        {

        	            		sqlOper->setValue(3/*uSQL::SQLOperator::GT*/);
        	            	  
        	        }


        	    }
        	    break;
        	case 4:
        	    // GQL.g:152:4: GT
        	    {
        	         MATCHT(GT, &FOLLOW_GT_in_condition_operator331);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecondition_operatorEx;
        	        }


        	        {

        	            		sqlOper->setValue(4/*uSQL::SQLOperator::LE*/);
        	            	  
        	        }


        	    }
        	    break;
        	case 5:
        	    // GQL.g:155:4: GE
        	    {
        	         MATCHT(GE, &FOLLOW_GE_in_condition_operator338);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecondition_operatorEx;
        	        }


        	        {

        	            		sqlOper->setValue(5/*uSQL::SQLOperator::GE*/);
        	            	  
        	        }


        	    }
        	    break;
        	case 6:
        	    // GQL.g:158:4: NOTEQ
        	    {
        	         MATCHT(NOTEQ, &FOLLOW_NOTEQ_in_condition_operator345);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecondition_operatorEx;
        	        }


        	        {

        	            		sqlOper->setValue(6/*uSQL::SQLOperator::NOTEQ*/);
        	            	  
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulecondition_operatorEx; /* Prevent compiler warnings */
    rulecondition_operatorEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return sqlOper;
}
/* $ANTLR end condition_operator */

/**
 * $ANTLR start sort_section
 * GQL.g:163:1: sort_section returns [uSQL::SQLOrderBy *sqlOrders] : ORDER BY sort_specification_list[sqlOrders] ;
 */
static uSQL::SQLOrderBy *
sort_section(pGQLParser ctx)
{
    uSQL::SQLOrderBy * sqlOrders;


    /* Initialize rule variables
     */


    		sqlOrders = new uSQL::SQLOrderBy();
    	
    {
        // GQL.g:167:2: ( ORDER BY sort_specification_list[sqlOrders] )
        // GQL.g:167:4: ORDER BY sort_specification_list[sqlOrders]
        {
             MATCHT(ORDER, &FOLLOW_ORDER_in_sort_section368);
            if  (HASEXCEPTION())
            {
                goto rulesort_sectionEx;
            }


             MATCHT(BY, &FOLLOW_BY_in_sort_section370);
            if  (HASEXCEPTION())
            {
                goto rulesort_sectionEx;
            }


            FOLLOWPUSH(FOLLOW_sort_specification_list_in_sort_section372);
            sort_specification_list(ctx, sqlOrders);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesort_sectionEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulesort_sectionEx; /* Prevent compiler warnings */
    rulesort_sectionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return sqlOrders;
}
/* $ANTLR end sort_section */

/**
 * $ANTLR start sort_specification_list
 * GQL.g:170:1: sort_specification_list[uSQL::SQLOrderBy *sqlOrders] : sort_specification[sqlOrders] ( AND sort_specification[sqlOrders] )* ;
 */
static void
sort_specification_list(pGQLParser ctx, uSQL::SQLOrderBy *sqlOrders)
{
    /* Initialize rule variables
     */

    {
        // GQL.g:171:2: ( sort_specification[sqlOrders] ( AND sort_specification[sqlOrders] )* )
        // GQL.g:171:4: sort_specification[sqlOrders] ( AND sort_specification[sqlOrders] )*
        {
            FOLLOWPUSH(FOLLOW_sort_specification_in_sort_specification_list387);
            sort_specification(ctx, sqlOrders);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesort_specification_listEx;
            }


            // GQL.g:171:34: ( AND sort_specification[sqlOrders] )*

            for (;;)
            {
                int alt10=2;
                switch ( LA(1) )
                {
                case AND:
                	{
                		alt10=1;
                	}
                    break;

                }

                switch (alt10)
                {
            	case 1:
            	    // GQL.g:171:35: AND sort_specification[sqlOrders]
            	    {
            	         MATCHT(AND, &FOLLOW_AND_in_sort_specification_list391);
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulesort_specification_listEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_sort_specification_in_sort_specification_list393);
            	        sort_specification(ctx, sqlOrders);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulesort_specification_listEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop10;	/* break out of the loop */
            	    break;
                }
            }
            loop10: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto rulesort_specification_listEx; /* Prevent compiler warnings */
    rulesort_specification_listEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end sort_specification_list */

/**
 * $ANTLR start sort_specification
 * GQL.g:174:1: sort_specification[uSQL::SQLOrderBy *sqlOrders] : property ( ordering_specification )? ;
 */
static void
sort_specification(pGQLParser ctx, uSQL::SQLOrderBy *sqlOrders)
{
    GQLParser_property_return property4;
    #undef	RETURN_TYPE_property4
    #define	RETURN_TYPE_property4 GQLParser_property_return

    GQLParser_ordering_specification_return ordering_specification5;
    #undef	RETURN_TYPE_ordering_specification5
    #define	RETURN_TYPE_ordering_specification5 GQLParser_ordering_specification_return

    /* Initialize rule variables
     */

    {
        // GQL.g:175:2: ( property ( ordering_specification )? )
        // GQL.g:175:4: property ( ordering_specification )?
        {
            FOLLOWPUSH(FOLLOW_property_in_sort_specification410);
            property4=property(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesort_specificationEx;
            }


            // GQL.g:175:13: ( ordering_specification )?
            {
                int alt11=2;
                switch ( LA(1) )
                {
                    case ASC:
                    case DESC:
                    	{
                    		alt11=1;
                    	}
                        break;
                }

                switch (alt11)
                {
            	case 1:
            	    // GQL.g:175:14: ordering_specification
            	    {
            	        FOLLOWPUSH(FOLLOW_ordering_specification_in_sort_specification413);
            	        ordering_specification5=ordering_specification(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulesort_specificationEx;
            	        }


            	    }
            	    break;

                }
            }

            {

                		uSQL::SQLOrder *sqlOrder = new uSQL::SQLOrder();
                		sqlOrder->setValue(CG_ANTLR3_STRING_2_UTF8((STRSTREAM->toStringTT(STRSTREAM, property4.start, property4.stop))
                ));
                		if (ordering_specification)
                			sqlOrder->setOrder(CG_ANTLR3_STRING_2_UTF8((STRSTREAM->toStringTT(STRSTREAM, ordering_specification5.start, ordering_specification5.stop))
                ));
                		sqlOrders->addChildNode(sqlOrder);
                	  
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulesort_specificationEx; /* Prevent compiler warnings */
    rulesort_specificationEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end sort_specification */

/**
 * $ANTLR start ordering_specification
 * GQL.g:184:1: ordering_specification : ( ASC | DESC );
 */
static GQLParser_ordering_specification_return
ordering_specification(pGQLParser ctx)
{
    GQLParser_ordering_specification_return retval;


    /* Initialize rule variables
     */

    retval.start = LT(1); retval.stop = retval.start;


    {
        // GQL.g:185:2: ( ASC | DESC )
        // GQL.g:
        {
            if ( LA(1) == ASC || LA(1) == DESC )
            {
                CONSUME();
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = NULL;

                goto ruleordering_specificationEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleordering_specificationEx; /* Prevent compiler warnings */
    ruleordering_specificationEx: ;
    retval.stop = LT(-1);


            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return retval;
}
/* $ANTLR end ordering_specification */

/**
 * $ANTLR start limit_section
 * GQL.g:189:1: limit_section returns [uSQL::SQLLimit *sqlLimit] : LIMIT ( limit_offset[sqlLimit] )? NUMBER ;
 */
static uSQL::SQLLimit *
limit_section(pGQLParser ctx)
{
    uSQL::SQLLimit * sqlLimit;


    pANTLR3_COMMON_TOKEN    NUMBER6;

    /* Initialize rule variables
     */


    		sqlLimit = new uSQL::SQLLimit();
    	
    NUMBER6       = NULL;

    {
        // GQL.g:193:2: ( LIMIT ( limit_offset[sqlLimit] )? NUMBER )
        // GQL.g:193:4: LIMIT ( limit_offset[sqlLimit] )? NUMBER
        {
             MATCHT(LIMIT, &FOLLOW_LIMIT_in_limit_section454);
            if  (HASEXCEPTION())
            {
                goto rulelimit_sectionEx;
            }


            // GQL.g:193:10: ( limit_offset[sqlLimit] )?
            {
                int alt12=2;
                switch ( LA(1) )
                {
                    case NUMBER:
                    	{
                    		switch ( LA(2) )
                    		{
                    		    case COMMA:
                    		    	{
                    		    		alt12=1;
                    		    	}
                    		        break;
                    		}

                    	}
                        break;
                }

                switch (alt12)
                {
            	case 1:
            	    // GQL.g:193:11: limit_offset[sqlLimit]
            	    {
            	        FOLLOWPUSH(FOLLOW_limit_offset_in_limit_section457);
            	        limit_offset(ctx, sqlLimit);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulelimit_sectionEx;
            	        }


            	    }
            	    break;

                }
            }

            NUMBER6 = (pANTLR3_COMMON_TOKEN) MATCHT(NUMBER, &FOLLOW_NUMBER_in_limit_section462);
            if  (HASEXCEPTION())
            {
                goto rulelimit_sectionEx;
            }


            {

                		uSQL::SQLExpression *countExpr = new uSQL::SQLExpression();
                		countExpr->setValue(CG_ANTLR3_STRING_2_UTF8((NUMBER6->getText(NUMBER6))));
                		sqlLimit->addChildNode(countExpr);
                	  
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulelimit_sectionEx; /* Prevent compiler warnings */
    rulelimit_sectionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return sqlLimit;
}
/* $ANTLR end limit_section */

/**
 * $ANTLR start limit_offset
 * GQL.g:200:1: limit_offset[uSQL::SQLLimit *sqlLimit] : NUMBER COMMA ;
 */
static void
limit_offset(pGQLParser ctx, uSQL::SQLLimit *sqlLimit)
{
    pANTLR3_COMMON_TOKEN    NUMBER7;

    /* Initialize rule variables
     */

    NUMBER7       = NULL;

    {
        // GQL.g:201:2: ( NUMBER COMMA )
        // GQL.g:201:4: NUMBER COMMA
        {
            NUMBER7 = (pANTLR3_COMMON_TOKEN) MATCHT(NUMBER, &FOLLOW_NUMBER_in_limit_offset477);
            if  (HASEXCEPTION())
            {
                goto rulelimit_offsetEx;
            }


             MATCHT(COMMA, &FOLLOW_COMMA_in_limit_offset479);
            if  (HASEXCEPTION())
            {
                goto rulelimit_offsetEx;
            }


            {

                		uSQL::SQLExpression *countExpr = new uSQL::SQLExpression();
                		countExpr->setValue(CG_ANTLR3_STRING_2_UTF8((NUMBER7->getText(NUMBER7))));
                		sqlLimit->addChildNode(countExpr);
                	
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulelimit_offsetEx; /* Prevent compiler warnings */
    rulelimit_offsetEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end limit_offset */

/**
 * $ANTLR start offset_section
 * GQL.g:208:1: offset_section returns [uSQL::SQLOffset *sqlOffset] : OFFSET NUMBER ;
 */
static uSQL::SQLOffset *
offset_section(pGQLParser ctx)
{
    uSQL::SQLOffset * sqlOffset;


    pANTLR3_COMMON_TOKEN    NUMBER8;

    /* Initialize rule variables
     */


    		sqlOffset = new uSQL::SQLOffset();
    	
    NUMBER8       = NULL;

    {
        // GQL.g:212:2: ( OFFSET NUMBER )
        // GQL.g:212:4: OFFSET NUMBER
        {
             MATCHT(OFFSET, &FOLLOW_OFFSET_in_offset_section502);
            if  (HASEXCEPTION())
            {
                goto ruleoffset_sectionEx;
            }


            NUMBER8 = (pANTLR3_COMMON_TOKEN) MATCHT(NUMBER, &FOLLOW_NUMBER_in_offset_section504);
            if  (HASEXCEPTION())
            {
                goto ruleoffset_sectionEx;
            }


            {

                		uSQL::SQLExpression *offsetExpr = new uSQL::SQLExpression();
                		offsetExpr->setValue(CG_ANTLR3_STRING_2_UTF8((NUMBER8->getText(NUMBER8))));
                		sqlOffset->addChildNode(offsetExpr);
                	  
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleoffset_sectionEx; /* Prevent compiler warnings */
    ruleoffset_sectionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return sqlOffset;
}
/* $ANTLR end offset_section */

/**
 * $ANTLR start property
 * GQL.g:224:1: property : ID ;
 */
static GQLParser_property_return
property(pGQLParser ctx)
{
    GQLParser_property_return retval;


    /* Initialize rule variables
     */

    retval.start = LT(1); retval.stop = retval.start;


    {
        // GQL.g:225:2: ( ID )
        // GQL.g:225:4: ID
        {
             MATCHT(ID, &FOLLOW_ID_in_property521);
            if  (HASEXCEPTION())
            {
                goto rulepropertyEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulepropertyEx; /* Prevent compiler warnings */
    rulepropertyEx: ;
    retval.stop = LT(-1);


            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return retval;
}
/* $ANTLR end property */

/**
 * $ANTLR start value
 * GQL.g:228:1: value : STRING ;
 */
static GQLParser_value_return
value(pGQLParser ctx)
{
    GQLParser_value_return retval;


    /* Initialize rule variables
     */

    retval.start = LT(1); retval.stop = retval.start;


    {
        // GQL.g:229:2: ( STRING )
        // GQL.g:229:4: STRING
        {
             MATCHT(STRING, &FOLLOW_STRING_in_value533);
            if  (HASEXCEPTION())
            {
                goto rulevalueEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulevalueEx; /* Prevent compiler warnings */
    rulevalueEx: ;
    retval.stop = LT(-1);


            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return retval;
}
/* $ANTLR end value */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
