/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : GQL.g
 *     -                            On : 2011-12-02 15:20:26
 *     -                for the parser : GQLParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser 
GQLParser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pGQLParser, which is returned from a call to GQLParserNew().
 *
 * The methods in pGQLParser are  as follows:
 *
 *  - 
 void
      pGQLParser->statement(pGQLParser)
 *  - 
 void
      pGQLParser->select_statement(pGQLParser)
 *  - 
 void
      pGQLParser->table_name(pGQLParser)
 *  - 
 uSQL::SQLFrom *
      pGQLParser->table_list(pGQLParser)
 *  - 
 uSQL::SQLWhere *
      pGQLParser->where_section(pGQLParser)
 *  - 
 void
      pGQLParser->condition_list(pGQLParser)
 *  - 
 void
      pGQLParser->condition(pGQLParser)
 *  - 
 uSQL::SQLExpression *
      pGQLParser->expression_atom(pGQLParser)
 *  - 
 uSQL::SQLOperator *
      pGQLParser->condition_operator(pGQLParser)
 *  - 
 uSQL::SQLOrderBy *
      pGQLParser->sort_section(pGQLParser)
 *  - 
 void
      pGQLParser->sort_specification_list(pGQLParser)
 *  - 
 void
      pGQLParser->sort_specification(pGQLParser)
 *  - 
 GQLParser_ordering_specification_return
      pGQLParser->ordering_specification(pGQLParser)
 *  - 
 uSQL::SQLLimit *
      pGQLParser->limit_section(pGQLParser)
 *  - 
 void
      pGQLParser->limit_offset(pGQLParser)
 *  - 
 uSQL::SQLOffset *
      pGQLParser->offset_section(pGQLParser)
 *  - 
 GQLParser_property_return
      pGQLParser->property(pGQLParser)
 *  - 
 GQLParser_value_return
      pGQLParser->value(pGQLParser)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_GQLParser_H
#define _GQLParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

	#include <string.h>
	#include <cybergarage/sql/SQLParser.h>
    
	#define CG_ANTLR3_STRING_2_UTF8(str) ((const char *)str->chars)
	#define CG_ANTLR3_STRING_2_INT(str) (str->chars ? atoi((const char *)str->chars) : 0)


#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct GQLParser_Ctx_struct GQLParser, * pGQLParser;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif
typedef struct GQLParser_ordering_specification_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
}
    GQLParser_ordering_specification_return;



typedef struct GQLParser_property_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
}
    GQLParser_property_return;



typedef struct GQLParser_value_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
}
    GQLParser_value_return;




/** Context tracking structure for 
GQLParser

 */
struct GQLParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;

     void
     (*statement)	(struct GQLParser_Ctx_struct * ctx, uSQL::SQLParser *sqlParser);

     void
     (*select_statement)	(struct GQLParser_Ctx_struct * ctx, uSQL::SQLStatement *sqlStmt);

     void
     (*table_name)	(struct GQLParser_Ctx_struct * ctx, uSQL::SQLFrom *sqlFrom);

     uSQL::SQLFrom *
     (*table_list)	(struct GQLParser_Ctx_struct * ctx);

     uSQL::SQLWhere *
     (*where_section)	(struct GQLParser_Ctx_struct * ctx);

     void
     (*condition_list)	(struct GQLParser_Ctx_struct * ctx, uSQL::SQLWhere *sqlWhere);

     void
     (*condition)	(struct GQLParser_Ctx_struct * ctx, uSQL::SQLWhere *sqlWhere);

     uSQL::SQLExpression *
     (*expression_atom)	(struct GQLParser_Ctx_struct * ctx);

     uSQL::SQLOperator *
     (*condition_operator)	(struct GQLParser_Ctx_struct * ctx);

     uSQL::SQLOrderBy *
     (*sort_section)	(struct GQLParser_Ctx_struct * ctx);

     void
     (*sort_specification_list)	(struct GQLParser_Ctx_struct * ctx, uSQL::SQLOrderBy *sqlOrders);

     void
     (*sort_specification)	(struct GQLParser_Ctx_struct * ctx, uSQL::SQLOrderBy *sqlOrders);

     GQLParser_ordering_specification_return
     (*ordering_specification)	(struct GQLParser_Ctx_struct * ctx);

     uSQL::SQLLimit *
     (*limit_section)	(struct GQLParser_Ctx_struct * ctx);

     void
     (*limit_offset)	(struct GQLParser_Ctx_struct * ctx, uSQL::SQLLimit *sqlLimit);

     uSQL::SQLOffset *
     (*offset_section)	(struct GQLParser_Ctx_struct * ctx);

     GQLParser_property_return
     (*property)	(struct GQLParser_Ctx_struct * ctx);

     GQLParser_value_return
     (*value)	(struct GQLParser_Ctx_struct * ctx);
    // Delegated rules

    const char * (*getGrammarFileName)();
    void            (*reset)  (struct GQLParser_Ctx_struct * ctx);
    void	    (*free)   (struct GQLParser_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pGQLParser GQLParserNew         (
pANTLR3_COMMON_TOKEN_STREAM
 instream);
ANTLR3_API pGQLParser GQLParserNewSSD      (
pANTLR3_COMMON_TOKEN_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
parser
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define A      4
#define ANCESTOR      5
#define AND      6
#define ASC      7
#define ASTERISK      8
#define B      9
#define BY      10
#define C      11
#define COMMA      12
#define COMMENT      13
#define D      14
#define DESC      15
#define DIGIT      16
#define E      17
#define EQ      18
#define EscapeSequence      19
#define F      20
#define FROM      21
#define G      22
#define GE      23
#define GT      24
#define H      25
#define I      26
#define ID      27
#define IN      28
#define IS      29
#define J      30
#define K      31
#define L      32
#define LE      33
#define LIMIT      34
#define M      35
#define N      36
#define NOTEQ      37
#define NUMBER      38
#define O      39
#define OFFSET      40
#define OP_LT      41
#define ORDER      42
#define P      43
#define Q      44
#define R      45
#define S      46
#define SELECT      47
#define STRING      48
#define T      49
#define U      50
#define V      51
#define W      52
#define WHERE      53
#define WS      54
#define X      55
#define Y      56
#define Z      57
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for GQLParser
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
