/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : UnQL.g
 *     -                            On : 2011-10-06 04:06:43
 *     -                 for the lexer : UnQLLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
UnQLLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pUnQLLexer, which is returned from a call to UnQLLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pUnQLLexer are  as follows:
 *
 *  - 
 void
      pUnQLLexer->NUMBER(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->COMMENT(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->WS(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->DIGIT(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->ASTERISK(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->EQ(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->OP_LT(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->LE(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->GT(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->GE(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->NOTEQ(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->COMMA(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->A(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->B(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->C(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->D(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->E(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->F(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->G(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->H(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->I(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->J(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->K(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->L(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->M(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->N(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->O(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->P(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->Q(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->R(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->S(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->T(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->U(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->V(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->W(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->X(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->Y(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->Z(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->ANCESTOR(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->AND(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->ASC(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->BY(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->DESC(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->FROM(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->IN(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->IS(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->LIMIT(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->OFFSET(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->ORDER(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->SELECT(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->WHERE(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->ID(pUnQLLexer)
 *  - 
 void
      pUnQLLexer->Tokens(pUnQLLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_UnQLLexer_H
#define _UnQLLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

	#include <cybergarage/sql/SQLParser.h>


#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct UnQLLexer_Ctx_struct UnQLLexer, * pUnQLLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
UnQLLexer

 */
struct UnQLLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mNUMBER)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mCOMMENT)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mDIGIT)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mASTERISK)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mEQ)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mOP_LT)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mLE)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mGT)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mGE)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mNOTEQ)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mCOMMA)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mA)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mB)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mC)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mD)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mE)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mF)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mG)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mH)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mI)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mJ)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mK)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mL)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mM)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mN)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mO)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mP)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mQ)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mR)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mS)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mT)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mU)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mV)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mW)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mX)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mY)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mZ)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mANCESTOR)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mAND)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mASC)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mBY)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mDESC)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mFROM)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mIN)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mIS)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mLIMIT)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mOFFSET)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mORDER)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mSELECT)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mWHERE)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mID)	(struct UnQLLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct UnQLLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct UnQLLexer_Ctx_struct * ctx);
    void	    (*free)   (struct UnQLLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pUnQLLexer UnQLLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pUnQLLexer UnQLLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define A      4
#define ANCESTOR      5
#define AND      6
#define ASC      7
#define ASTERISK      8
#define B      9
#define BY      10
#define C      11
#define COMMA      12
#define COMMENT      13
#define D      14
#define DESC      15
#define DIGIT      16
#define E      17
#define EQ      18
#define F      19
#define FROM      20
#define G      21
#define GE      22
#define GT      23
#define H      24
#define I      25
#define ID      26
#define IN      27
#define IS      28
#define J      29
#define K      30
#define L      31
#define LE      32
#define LIMIT      33
#define M      34
#define N      35
#define NOTEQ      36
#define NUMBER      37
#define O      38
#define OFFSET      39
#define OP_LT      40
#define ORDER      41
#define P      42
#define Q      43
#define R      44
#define S      45
#define SELECT      46
#define T      47
#define U      48
#define V      49
#define W      50
#define WHERE      51
#define WS      52
#define X      53
#define Y      54
#define Z      55
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for UnQLLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
